name: nosql_dart_server
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.0

# Add regular dependencies here.
dependencies:
  args: ^2.4.0
  async: ^2.13.0
  bcrypt: ^1.1.3
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  shelf_static: ^1.1.0
  synchronized: ^3.4.0
  uuid: ^4.3.0 # Para gerar IDs únicos

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
